ci: prevent jobs from stopping on every fail
Before, the job wouldn't finish every test before stopping. The
results of the tests will take a bit longer, but report at the end
will be more complete.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,8 +20,19 @@ jobs:
 
     - name: Build the application
       run: |
+        set +e
+        failed=0
         for service in $(ls -d ./services/*/); do
           echo "::group::Building $service..."
           go build -v $service/cmd/main.go
-          echo "::endgroup::"
+          if [ $? -ne 0 ]; then
+            echo "::endgroup::"
+            echo "::error::Failed to build $service"
+            failed=1
+          else
+            echo "::endgroup::"
+          fi
         done
+        if [ $failed != 0 ]; then
+          exit 1
+        fi
diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -23,11 +23,28 @@ jobs:
     
     - name: Run integration tests
       run: |
+        set +e
+        failed=0
         echo "::group::Running integration tests for ./common/..."
         go test -tags=integration -v ./common/...
-        echo "::endgroup::"
+        if [ $? -ne 0 ]; then
+          echo "::endgroup::"
+          echo "::error::Failed to build $service"
+          failed=1
+        else
+          echo "::endgroup::"
+        fi
         for service in $(ls -d ./services/*/); do
           echo "::group::Running integration tests for $service..."
           go test -tags=integration -v $service...
-          echo "::endgroup::"
+          if [ $? -ne 0 ]; then
+            echo "::endgroup::"
+            echo "::error::Failed to build $service"
+            failed=1
+          else
+            echo "::endgroup::"
+          fi
         done
+        if [ $failed != 0 ]; then
+          exit 1
+        fi
diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -14,17 +14,34 @@ jobs:
       uses: actions/checkout@v5
 
     - name: Set up Go
-      uses: actions/setup-go@v4
+      uses: actions/setup-go@v5
       with:
         go-version: '1.26'
     
     - name: Run unit tests
       run: |
+        set +e
+        failed=0
         echo "::group::Running unit tests for ./common/..."
         go test -v ./common/...
-        echo "::endgroup::"
+        if [ $? -ne 0 ]; then
+          echo "::endgroup::"
+          echo "::error::Failed to build $service"
+          failed=1
+        else
+          echo "::endgroup::"
+        fi
         for service in $(ls -d ./services/*/); do
           echo "::group::Running unit tests for $service..."
           go test -v $service...
-          echo "::endgroup::"
+          if [ $? -ne 0 ]; then
+            echo "::endgroup::"
+            echo "::error::Failed to build $service"
+            failed=1
+          else
+            echo "::endgroup::"
+          fi
         done
+        if [ $failed != 0 ]; then
+          exit 1
+        fi
